# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d43386a5d0905d1ccab417921e93f39bdf5ace723450e025b103d6e4ad90e6ec7ef1d7877c7a089dccd18c9fafda52870ecc8c5edaca450c9fefbce93db13b7c

test:
  secret_key_base: 3dbf9288ef228952f47bf119a4bda38196acbc115048b50339ff4235e07fe08682c7f0b704cc647f1e4cb09c1285b48df89316b6be0c2605c8af3eff3924000a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
